[general]
import = [
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[terminal.shell]
program = "/Users/evan/.local/share/devbox/global/default/.devbox/nix/profile/default/bin/fish"
args = ["-l"]

[env]
TERM = "xterm-256color"
SHELL = "/Users/evan/.local/share/devbox/global/default/.devbox/nix/profile/default/bin/fish"

[window]
startup_mode = "Maximized"

[font]
size = 12
normal = { family = "JetBrains Mono", style = "Light" }
offset = { x = 1, y = 1 }

[keyboard]
bindings = [
  { key = "f", mods = "Command|Control", action = "ToggleSimpleFullscreen" }
]
