# https://github.com/helix-editor/helix/blob/master/book/src/configuration.md
theme = "dracula"

[editor]
line-number = "absolute"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
