# https://github.com/helix-editor/helix/blob/master/book/src/configuration.md
# https://github.com/langston-barrett/spacelix/blob/main/src/spacelix.toml
theme = "catppuccin_mocha"

[editor]
bufferline = "never" # turns out this is more distracting than I expected
color-modes = true
line-number = "absolute"
scrolloff = 2

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "version-control"]

[editor.whitespace.render]
newline = "none"
space = "none"
tab = "all"

[editor.whitespace.characters]
tab = "›"

[keys.normal]
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
A-x = "command_palette"
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
C-r = "redo"

[keys.normal.space]
"space" = "file_picker"
"," = "buffer_picker"

[keys.normal.space.q]
a = ":quit-all"
q = ":quit"

# Buffers
[keys.normal.space.b]
b = "buffer_picker"
d = ":buffer-close"
D = ":buffer-close!"
n = "goto_next_buffer"
p = "goto_previous_buffer"

# Jumplist
[keys.normal.space.j]
"b" = "jump_backward"
"f" = "jump_forward"
"j" = "jumplist_picker"
"s" = "save_selection"

[keys.select]
"$" = "goto_line_end"

[keys.normal.g]
"q" = ":reflow"
