# https://github.com/helix-editor/helix/blob/master/book/src/configuration.md
theme = "catppuccin_mocha"

[editor]
line-number = "absolute"
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"

[keys.normal.space]
"space" = "file_picker"
"," = "buffer_picker"

# [keys.normal.space.b]
# b = "buffer_picker"
# d = "buffer_close"
