gui:
  showBottomLine: true
  showCommandLog: false
  showFileTree: false
  showRandomTip: false
  theme:
    selectedLineBgColor:
      - default
git:
  diffRenderers:
    - colorArg: always
      command: delta --dark --paging=never --line-numbers
