" Enable ligatures in MacVim if possible.
if exists("&macligatures")
  set macligatures
endif

if exists("&macmeta")
  set macmeta
endif

" Gimme that sweet, sweet font.
set guifont=IBM\ Plex\ Mono\ 9

set guioptions-=e " Gimme those Vim-native tabs, damnit!
set guioptions-=T " GTFO with that toolbar.
set guioptions-=m " GTFO with that menu bar.
set guioptions-=r " Remove
set guioptions-=l " all
set guioptions-=R " the
set guioptions-=L " scrollbars.
